#Storing indexes, search artifacts, and configuration changes

version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  so1-var:
  so1-etc:

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: splunk/splunk:latest
    container_name: so1
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=<password>
      - DEBUG=true
    ports:
      - 8000:8000
      - 8089:8089
    volumes:
      - so1-var:/opt/splunk/var
      - so1-etc:/opt/splunk/etc